FROM php:5.6.29-apache

MAINTAINER Stephan Altmann <stephan@salty.rocks>

#create folder structure
RUN mkdir /var/www/shopware
RUN mkdir /var/log/apache-php

#set permissions
RUN chown -R www-data:www-data /var/www
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data

#add host config
ADD vhosts/000-default.conf /etc/apache2/sites-enabled/000-default.conf
ADD vhosts/shopware.conf /etc/apache2/sites-enabled/shopware.conf

#install php extensions
RUN docker-php-ext-install pdo_mysql 
RUN apt-get update && \
            apt-get install -y libfreetype6-dev libjpeg62-turbo-dev && \
            docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/  &&  \
            docker-php-ext-install gd
RUN docker-php-ext-install zip

#php-settings
RUN touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "upload_max_filesize = 10M;" >> /usr/local/etc/php/conf.d/uploads.ini
RUN touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "memory_limit = 1024M;" >> /usr/local/etc/php/conf.d/uploads.ini
RUN a2enmod rewrite
