FROM php:7.2-apache

MAINTAINER Stephan Altmann <stephan@salty.rocks>

#install needed tools
RUN apt-get update && apt-get install -y wget

#create folder structure
RUN mkdir /var/www/shopware
RUN mkdir /var/www/shopware/engine
RUN mkdir /var/www/shopware/engine/Shopware
RUN mkdir /var/www/shopware/engine/Shopware/Plugins
RUN mkdir /var/log/apache-php

#set permissions
RUN chown -R www-data:www-data /var/www
RUN chmod -R 777 /var/www/shopware/engine/Shopware/Plugins/
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_RUN_DIR /var/run/apache2

#add host config
ADD vhosts/000-default.conf /etc/apache2/sites-enabled/000-default.conf
ADD vhosts/shopware.conf /etc/apache2/sites-enabled/shopware.conf

#install php extensions
RUN docker-php-ext-install pdo_mysql
RUN apt-get update && \
            apt-get install -y libssh2-1-dev libssh2-1 libfreetype6-dev libjpeg62-turbo-dev libxml2-dev  && \
            docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/  &&  \
            docker-php-ext-install gd
RUN docker-php-ext-install zip soap
RUN pecl install ssh2-1.1.2




#install vim
RUN apt-get install -y vim

#php-settings
RUN touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "upload_max_filesize = 10M;" >> /usr/local/etc/php/conf.d/uploads.ini
RUN touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "memory_limit = 1024M;" >> /usr/local/etc/php/conf.d/uploads.ini
RUN touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "max_execution_time = 300;" >> /usr/local/etc/php/conf.d/uploads.ini
RUN a2enmod rewrite

#xdebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.idekey=phpstorm" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini

#composer
RUN echo "Install composer"
RUN curl --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#setup grunt
RUN apt-get install -y gnupg2
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN echo "Install NPM"
RUN apt-get install -y nodejs
RUN npm install -g grunt-cli

WORKDIR /var/www/shopware
