version: '2'

services:
  apache-php:
    build: ./apache-php
    volumes:
      - ./repositories/shopware:/var/www/shopware
      - ./apache-php/logs:/var/log/apache-php
      #- ./repositories/theme:/var/www/shopware/themes/Frontend/${THEME}
      - ./apache-php/logs/apache2:/var/log/apache2
      - ./certs:/etc/apache2/ssl
      - ./tmp:/tmp
    environment:
      DOMAIN_NAME: "shopware.test"
      XDEBUG_CONFIG: remote_host=${IP}.5.254
    networks:
      static-network:
        ipv4_address: ${IP}.1.1
    ports:
    - "80:80"
    - "9000:9000"
    extra_hosts:
    - "shopware.test:127.0.0.1"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: shopware
    volumes:
    - ./db-dump:/docker-entrypoint-initdb.d
    - ./scripts:/usr/local/bin/export
    networks:
      static-network:
        ipv4_address: ${IP}.1.2
    ports:
    - "3306:3306"

networks:
  static-network:
    driver: bridge
    ipam:
      config:
      - subnet: ${IP}.0.0/16
        gateway: ${IP}.5.254
